
GET http://localhost:3000/

###

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzOTg3YmNlZGUwYTdlOWZjMjBiNmEzOCIsIm5hbWUiOiJDbGVtZW50IiwiZW1haWwiOiJ0ZXN0LnRlc3RAZ21haWwuY29tIiwiX192IjowfSwiaWF0IjoxNjcwOTM3NTYwLCJleHAiOjE2NzEwMjM5NjB9.ljP76XjrM0zXlyV19WyyS85uGpWtSoLqfHt-mdMFXsg

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Clement",
    "email": "test.test@gmail.com",
    "password": "azerty1234"
}

###

POST http://localhost:3000/users/auth
Content-Type: application/json

{
  "id": "63987bcede0a7e9fc20b6a38",
  "password": "azerty1234"
}

### 

GET http://localhost:3000/users/6396daed8ff14add2baada33

###
PATCH http://localhost:3000/users/6396daed8ff14add2baada33
Content-Type: application/json

{
    "name": "Osman"
}

###

DELETE http://localhost:3000/users/6396daed8ff14add2baada33

###

DELETE http://localhost:3000/users

