
GET http://localhost:3000/

###

GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Clement",
    "email": "test.test@gmail.com",
    "password": "azerty123"
}

###

POST http://localhost:3000/users/auth
Content-Type: application/json

{
  "id": "63984f6ab951c301b885c56b",
  "password": "azerty123"
}


### 

GET http://localhost:3000/users/6396daed8ff14add2baada33

###
PATCH http://localhost:3000/users/6396daed8ff14add2baada33
Content-Type: application/json

{
    "name": "Osman"
}

###

DELETE http://localhost:3000/users/6396daed8ff14add2baada33
