
GET http://localhost:3000/

###

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzOTg4ZjAzMzA5YjM2ZWM5Mzg2ZjE4ZiIsIm5hbWUiOiJUZXN0IiwiZW1haWwiOiJ0ZXN0LnRlc3RAZ21haWwuY29tIiwiX192IjowfSwiaWF0IjoxNjcwOTQyNDk0LCJleHAiOjE2NzEwMjg4OTR9.7hStTPy6dDrqottmrJpOZJohR9M_h3qQ5OPKWNGXQ8o

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Test",
    "email": "test.test@gmail.com",
    "password": "azerty1234"
}

###

POST http://localhost:3000/users/auth
Content-Type: application/json

{
  "id": "63988f03309b36ec9386f18f",
  "password": "azerty1234"
}

### 

GET http://localhost:3000/users/6396daed8ff14add2baada33

###
PATCH http://localhost:3000/users/6396daed8ff14add2baada33
Content-Type: application/json

{
    "name": "Osman"
}

###

DELETE http://localhost:3000/users/6396daed8ff14add2baada33

###

DELETE http://localhost:3000/users

